name: 🚀 Deploy website on push
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.ponceleon.club:21
        username: ponce-demos_deploy_develop@ponceleon.club
        password: ${{ secrets.DEVELOP_FTP_PASSWORD }}
